WebApp/Controllers/AnimalController.cs
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class AnimalController : Controller
    {

        private Sistema s = Sistema.GetInstancia();

        [HttpGet]
        public IActionResult LibresListado()
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            List<Animal> a = s.GetAnimalesLibres();
            return View(a);
        }

        [HttpGet]
        public IActionResult AltaBovino()
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            return View();
        }
        [HttpPost]
        public IActionResult AltaBovino(Bovino b)
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            try
            {
                s.AltaAnimal(b);
                ViewBag.Message = "Alta de bovino exitosa";
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View();
        }

        [HttpGet]
        public IActionResult Vacunar()
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Peon")
            {
                return RedirectToAction("Logout", "Home");
            }
            List<Vacuna> vacunas = s.GetVacunas();
            return View(vacunas);
        }
        [HttpPost]
        public IActionResult Vacunar(string idCaravana, int idVacuna)
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Peon")
            {
                return RedirectToAction("Logout", "Home");
            }
            try
            {
                Animal? a = s.GetAnimalPorNumeroCaravana(idCaravana);
                Vacuna? v = s.GetVacunaPorId(idVacuna);
                if (a == null) throw new Exception("No se encontro el animal. ");
                if (v == null) throw new Exception("No se encontro la vacuna. ");
                a.VacunarAnimal(v);
                ViewBag.Message = "Vacunacion registrada exitosamente. ";
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message + "Revise los datos e intentelo nuevamente. ";
            }
            List<Vacuna> vacunas = s.GetVacunas();
            return View(vacunas);
        }

        [HttpGet]
        public IActionResult AsignarPotrero(int id)
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            Animal? a = s.GetAnimalPorId(id);
            if (a != null) ViewBag.NumeroCaravana = a.NumeroCaravana;
            return View(s.GetPotreros());
        }
        [HttpPost]
        public IActionResult AsignarPotrero(string idCaravana, int idPotrero)
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            try
            {
                Animal? a = s.GetAnimalPorNumeroCaravana(idCaravana);
                Potrero? p = s.GetPotreroPorId(idPotrero);
                if (a == null) throw new Exception("No se encontro el animal. ");
                if (p == null) throw new Exception("No se encontro el potrero. ");
                s.AddAnimalToPotrero( a , p );
                ViewBag.Message = $"{a.GetTipo()} con caravana {idCaravana} asignado al potrero #{idPotrero}.";
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message + " // Revise los datos e intentelo nuevamente. ";
            }
            IEnumerable<Potrero> potreros = s.GetPotreros();
            return View(potreros);
        }

        [HttpGet]
        public IActionResult ListadoFiltrado()
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            return View(); 
        }
        [HttpPost]
        public IActionResult ListadoFiltrado(string tipoAnimal, double pesoAnimal)
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            if ((tipoAnimal != "Bovino" && tipoAnimal != "Ovino") || pesoAnimal <= 0)
            {
                ViewBag.Message = "Revise los datos ingresados.";
                return View();
            }
            else
            {
                IEnumerable<Animal> animales = s.GetAnimalesPorTipoYPeso(tipoAnimal, pesoAnimal);
                if(!animales.Any())
                {
                    ViewBag.Message = "No se encontraron animales con estos parametros.";
                    return View();
                }
                else
                {
                    ViewBag.TipoAnimal = tipoAnimal;
                    return View(animales);
                }
            }
        }
    }
}

WebApp/Controllers/EmpleadoController.cs
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class EmpleadoController : Controller
    {
        Sistema s = Sistema.GetInstancia();

        // GET: EmpleadoController
        [HttpGet]
        public IActionResult PeonesListado()
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            return View(s.GetPeones());
        }

        [HttpGet]
        public IActionResult Perfil(int id)
        {
            if (HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserID") != id.ToString())
            {
                return RedirectToAction("Logout", "Home");
            }
            Empleado? e = s.GetEmpleadoPorId(id);
            return View(e);
        }

        [HttpGet]
        public IActionResult Tareas(int id)
        {
            if (HttpContext.Session.GetString("loggedUserRole") == "Peon" && 
                HttpContext.Session.GetString("loggedUserID") != id.ToString() ||
                HttpContext.Session.GetString("loggedUserEmail") == null)
            {
                return RedirectToAction("Logout", "Home");
            }

            Peon? p = s.GetPeonPorId(id);
            if (p == null) return View();
            ViewBag.NombrePeon = p.Nombre;
            IEnumerable<Tarea> tareas = p.GetTareas();
            return View(tareas);
        }

        [HttpGet]
        public IActionResult AsignarTarea(int id)
        {
            if (HttpContext.Session.GetString("loggedUserRole") == null ||
                HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz" ||
                id == 0)
            {
                return RedirectToAction("Logout", "Home");
            }
            try
            {
                Peon? p = s.GetPeonPorId(id);
                if (p == null) throw new Exception("Peon no encontrado");
                ViewBag.NombrePeon = p.Nombre;
                ViewBag.PeonId = p.Id;
            }
            catch (Exception e)
            {
                ViewBag.MessageError = e.Message;
            }
            return View();
        }

        [HttpPost]
        public IActionResult AsignarTarea([FromForm] Tarea t, [FromForm] int PeonId) //este detalle del [FromForm] permite recibir un objeto con el model binding y tambien recibir otro parametro a la vez
        {
            if (HttpContext.Session.GetString("loggedUserRole") == null ||
                HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }

            try
            {
                Peon? p = s.GetPeonPorId(PeonId);
                if (p == null) throw new Exception("Peon no encontrado");
                ViewBag.NombrePeon = p.Nombre;
                ViewBag.PeonId = p.Id;
                s.AddTareaToPeon(t, p);
                ViewBag.MessageExito = $"Tarea #{t.Id} asignada correctamente";
            }
            catch (Exception e)
            {
                ViewBag.MessageError = e.Message;
            }

            return View();
        }

        [HttpGet]
        public IActionResult CerrarTarea(int id)
        {
            if (HttpContext.Session.GetString("loggedUserRole") == null ||
                HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserID") != id.ToString() ||
                HttpContext.Session.GetString("loggedUserRole") != "Peon")
            {
                return RedirectToAction("Logout", "Home");
            }
            Peon? p = s.GetPeonPorId(id);
            if (p != null)
            {
                ViewBag.IdPeon = p.Id;
                IEnumerable<Tarea> tareas = p.GetTareasPendientes();
                return View(tareas);
            }
            return View();
        }

        [HttpPost]
        public IActionResult CerrarTarea(int id, int idTarea, string comentario)
        {
            if (HttpContext.Session.GetString("loggedUserRole") == null ||
                HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserID") != id.ToString() ||
                HttpContext.Session.GetString("loggedUserRole") != "Peon")
            {
                return RedirectToAction("Logout", "Home");
            }
            List<Tarea> tareas = new List<Tarea>();
            Peon? p = s.GetPeonPorId(id);
            try
            {
                Tarea? t;
                ViewBag.IdPeon = p.Id;
                
                if (p == null) throw new Exception("No se encontro el peon.");
                t = p.GetTareaPorId(idTarea);
                if (t == null) throw new Exception("Debe seleccionar una tarea");
                t.CerrarTarea(comentario);
                ViewBag.MessageExito = $"Tarea #{t.Id} cerrada correctamente";
            }
            catch (Exception e)
            {
                ViewBag.MessageError = e.Message;
            }
            tareas = p.GetTareasPendientes();
            return View(tareas);
            
        }
    }
}

WebApp/Controllers/PotreroController.cs
using Dominio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class PotreroController : Controller
    {
        Sistema s = Sistema.GetInstancia();
        // GET: PotreroController
        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("loggedUserRole") == null ||
                HttpContext.Session.GetString("loggedUserEmail") == null ||
                HttpContext.Session.GetString("loggedUserRole") != "Capataz")
            {
                return RedirectToAction("Logout", "Home");
            }
            IEnumerable<Potrero> potrerosOrdenados = s.GetPotrerosOrdenadosPorCapacidadYCantidad(); 
            return View(potrerosOrdenados);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]- Sistema de Gestion Estanciera</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
    <link rel="icon" type="image/x-icon" href="/img/favicon.ico" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Login">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (Context.Session.GetString("loggedUserEmail") != null 
                            && Context.Session.GetString("loggedUserRole") == "Peon")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Empleado" asp-action="Perfil" asp-route-id="@Context.Session.GetString("loggedUserID")">
                                    Perfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Empleado" asp-action="CerrarTarea" asp-route-id="@Context.Session.GetString("loggedUserID")">
                                    Cerrar Tareas
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Animal" asp-action="Vacunar">
                                    Vacunar Animal</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Logout">
                                    Cerrar Sesion
                                </a>
                            </li>
                        }
                        else if (Context.Session.GetString("loggedUserEmail") != null 
                                && Context.Session.GetString("loggedUserRole") == "Capataz")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Empleado" asp-action="PeonesListado">
                                    Listado de Peones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Animal" asp-action="AltaBovino">
                                    Alta Bovino</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Animal" asp-action="LibresListado">
                                    Animales Libres</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Animal" asp-action="ListadoFiltrado">
                                    Listado Filtrado</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Potrero" asp-action="Index">
                                    Ver Potreros</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Animal" asp-action="AsignarPotrero">
                                    Asignar Potrero
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Logout">
                                    Cerrar Sesion
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebApp - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>